services:
  database:
    container_name: lumina-cloud-database
    image: "postgres:13-alpine"
    environment:  
      POSTGRES_DB: "${DATABASE__NAME}"
      POSTGRES_USER: "${DATABASE__USER}"
      POSTGRES_PASSWORD: "${DATABASE__PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./var/postgres:/var/lib/postgresql/data
    ports:
      - ${DATABASE__PORT}:${DATABASE__PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE__USER} -d ${DATABASE__NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s